"""SEO optimization: titles, descriptions, tags, hashtags, chapters.

LLM-polished when available; deterministic engine otherwise. All outputs
respect YouTube constraints (title <= 100 chars, tags <= 500 chars total).

v1.3 upgrades:
  - SEO is ALWAYS written in `settings.seo_language` (English by default)
    regardless of the video's narration language. This maximises search
    reach — an Urdu-narrated video still gets English tags / description
    so it shows up in global search.
  - When `hide_hooks_in_description` is True, the description describes
    WHAT the video covers WITHOUT restating the hook line. Competitors
    can't reverse-engineer the retention hook from the description.
  - The LLM prompt asks for professional, non-clickbaity titles and
    keyword-front-loaded descriptions with chapters. Hashtags are limited
    to 3 high-value ones.
  - Tags include the channel name + niche + topic-derived keywords +
    trending keywords (passed in via `trending_keywords`).
"""
from __future__ import annotations

from ..config import settings
from ..core.logging import get_logger
from ..core.utils import clamp
from . import llm

log = get_logger("seo")

MAX_TAGS_CHARS = 500


def _pack_tags(candidates: list[str]) -> list[str]:
    out, total = [], 0
    for t in candidates:
        t = t.strip().lower()
        if not t or t in out:
            continue
        if total + len(t) + 1 > MAX_TAGS_CHARS:
            break
        out.append(t)
        total += len(t) + 1
    return out


def _chapters(scenes: list[dict], scene_starts: list[float] | None) -> str:
    lines = []
    for i, sc in enumerate(scenes):
        start = int(scene_starts[i]) if scene_starts and i < len(scene_starts) else 0
        label = sc.get("beat", f"Part {i}").replace("_", " ").title()
        lines.append(f"{start // 60:02d}:{start % 60:02d} {label}")
    return "\n".join(lines)


async def optimize(
    script: dict, niche: str, scene_starts: list[float] | None = None,
    title_pattern_hint: str = "",
    trending_keywords: list[str] | None = None,
    channel_name: str = "",
) -> dict:
    """Generate SEO metadata for a video.

    `trending_keywords` comes from the YouTube monitor — keywords observed
    in top-performing videos of this niche. They are merged into the tag
    list so the video shows up alongside proven winners.
    """
    topic = script["topic"]
    titles = script.get("title_options") or [topic]
    keywords = [k for k in script.get("keywords", [])] or [
        w for w in topic.lower().split() if len(w) > 3
    ]
    # Merge in trending keywords from the monitor.
    if trending_keywords:
        keywords = list(dict.fromkeys([*keywords, *trending_keywords]))[:14]
    seo_lang = settings.seo_language or "en"
    hide_hooks = settings.hide_hooks_in_description

    hide_block = ""
    if hide_hooks:
        hide_block = (
            "IMPORTANT: do NOT restate the hook line or the open-loop question "
            "in the description. The description should tell viewers WHAT they "
            "will learn and WHY it matters, without revealing the curiosity gap. "
            "This protects the retention strategy from being copied."
        )

    channel_block = (
        f" The channel name is '{channel_name}' — include it once naturally in the description "
        f"and add it as the first tag." if channel_name else ""
    )

    data = await llm.chat_json([
        {"role": "system", "content": (
            f"You are a YouTube SEO expert. Respond ONLY with JSON: "
            f"{{title (<=95 chars, keyword front-loaded, no clickbait lies, professional tone), "
            f"description (2 short paragraphs in {seo_lang} + CTA, <=3500 chars), "
            f"tags (array, <=14, lowercase, in {seo_lang}), "
            f"hashtags (array, <=3, with #, in {seo_lang})}}. "
            f"{hide_block}{channel_block}"
        )},
        {"role": "user", "content": (
            f"Topic: {topic}\nNiche: {niche}\nCandidate titles: {titles}\n"
            f"Keywords: {keywords}\nTrending keywords in this niche: {trending_keywords or []}\n"
            f"Title pattern hint from channel learning: {title_pattern_hint or 'none'}\n"
            f"SEO language: {seo_lang}"
        )},
    ], temperature=0.6)

    chapters = _chapters(script.get("scenes", []), scene_starts)

    if isinstance(data, dict) and data.get("title"):
        log.info("SEO generated by LLM (lang=%s, hide_hooks=%s)", seo_lang, hide_hooks)
        return {
            "title": clamp(str(data["title"]), 95),
            "description": clamp(str(data.get("description", "")), 4500)
                           + f"\n\n--- Chapters ---\n{chapters}",
            "tags": _pack_tags([str(t) for t in data.get("tags", [])]),
            "hashtags": [str(h) for h in data.get("hashtags", [])][:3],
            "chapters": chapters,
            "engine": "llm",
            "seo_language": seo_lang,
        }

    # Template fallback — still English, still professional.
    title = clamp(titles[0], 95)
    # When hide_hooks is on, the template description focuses on the topic
    # rather than the hook line.
    topic_para = (
        f"In this video we break down {topic.lower()} — what it is, why it matters, "
        f"and the part most people miss. Stay to the end for the key takeaway."
    )
    description = (
        f"{topic_para}\n\n"
        f"Subscribe for a new video every day.\n\n"
        f"--- Chapters ---\n{chapters}"
    )
    tags = _pack_tags([
        channel_name.lower() if channel_name else None,
        topic, niche, f"{niche} explained", *keywords,
        "explained", "documentary", "2026",
    ])
    hashtags = [f"#{niche.replace(' ', '')}", "#explained", "#phoenixai"][:3]
    log.info("SEO generated by template engine (lang=%s)", seo_lang)
    return {
        "title": title, "description": description, "tags": tags,
        "hashtags": hashtags, "chapters": chapters, "engine": "template",
        "seo_language": seo_lang,
    }
