"""v1.4 monetization endpoints — Phase 1 features.

Exposes the 5 Phase 1 monetization services to the dashboard:

  GET  /api/monetization/upload-times/{channel_id}
       Best upload time AI — top 3 hours per weekday.

  POST /api/monetization/hook-analyze/{video_id}
       Re-run the hook analyzer on an existing video's script.

  POST /api/monetization/copyright-check/{video_id}
       Re-run the pre-upload copyright check on a rendered video.

  GET  /api/monetization/thumbnail-variants/{video_id}
       List the A/B thumbnail variants with their CTR predictions.

  POST /api/monetization/thumbnail-variants/{video_id}/regenerate
       Regenerate the A/B variants (e.g. after editing the title).

  POST /api/monetization/thumbnail-variants/{video_id}/pick/{variant_index}
       Manually pick a variant as the active thumbnail.
"""
from __future__ import annotations

from pathlib import Path

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from ..core.logging import get_logger
from ..models import Channel, Video
from ..services import (copyright_check as copyright_check_svc,
                        hook_analyzer as hook_analyzer_svc,
                        thumbnail_ai as thumbnail_ai_svc,
                        upload_time_ai as upload_time_ai_svc)
from .deps import get_db

log = get_logger("routes_monetization")
router = APIRouter(prefix="/api/monetization", tags=["monetization"])


@router.get("/upload-times/{channel_id}")
def upload_times(channel_id: int, db: Session = Depends(get_db)):
    """Best upload time AI — top 3 hours per weekday + overall best."""
    if not db.get(Channel, channel_id):
        raise HTTPException(404, "channel not found")
    return upload_time_ai_svc.suggest_best_hours(channel_id, top_n=3)


@router.get("/upload-times/{channel_id}/next")
def next_upload_time(channel_id: int, db: Session = Depends(get_db)):
    """Suggest the single best next upload time given the current time."""
    if not db.get(Channel, channel_id):
        raise HTTPException(404, "channel not found")
    return upload_time_ai_svc.suggest_next_upload_time(channel_id)


@router.post("/hook-analyze/{video_id}")
async def re_analyze_hook(video_id: int, db: Session = Depends(get_db)):
    """Re-run the hook analyzer on a video's existing script."""
    v = db.get(Video, video_id)
    if not v:
        raise HTTPException(404, "video not found")
    script = v.script_json or {}
    scenes = script.get("scenes") or []
    if not scenes:
        raise HTTPException(400, "video has no script — cannot analyze hook")
    first = scenes[0] if isinstance(scenes[0], dict) else {}
    narration = first.get("narration", "")
    if not narration:
        raise HTTPException(400, "first scene has no narration")
    result = await hook_analyzer_svc.analyze_hook(
        topic=v.topic, niche=v.niche,
        hook_narration=narration,
        hook_style=script.get("hook_style"),
        target_seconds=int(v.duration_seconds or 150),
    )
    # Persist the score on the video.
    v.hook_score = result.get("score")
    script["hook_analysis"] = result
    v.script_json = script
    db.commit()
    return result


@router.post("/copyright-check/{video_id}")
async def re_check_copyright(video_id: int, db: Session = Depends(get_db)):
    """Re-run the pre-upload copyright check on a rendered video."""
    v = db.get(Video, video_id)
    if not v:
        raise HTTPException(404, "video not found")
    if not v.file_path or not Path(v.file_path).exists():
        raise HTTPException(400, "video file not rendered yet")
    result = await copyright_check_svc.check_video(v.file_path)
    v.copyright_check_passed = result.get("clean") if result.get("checked") else None
    v.copyright_check_score = result.get("score")
    v.copyright_check_meta = result
    db.commit()
    return result


@router.get("/thumbnail-variants/{video_id}")
def list_thumbnail_variants(video_id: int, db: Session = Depends(get_db)):
    """List the A/B thumbnail variants for a video.

    Returns the variant paths + any predicted CTR scores stored on the
    video's thumbnail_variants field. (The variants themselves are just
    file paths; the CTR prediction lives in the seo_json field under
    `thumbnail_analysis` when generated by the orchestrator.)
    """
    v = db.get(Video, video_id)
    if not v:
        raise HTTPException(404, "video not found")
    paths = v.thumbnail_variants or ([v.thumbnail_path] if v.thumbnail_path else [])
    return {
        "video_id": video_id,
        "active_thumbnail": v.thumbnail_path,
        "predicted_ctr": v.predicted_ctr,
        "variants": [{"index": i, "path": p} for i, p in enumerate(paths)],
    }


@router.post("/thumbnail-variants/{video_id}/regenerate", status_code=202)
async def regenerate_thumbnail_variants(video_id: int, background: BackgroundTasks,
                                         db: Session = Depends(get_db)):
    """Regenerate the A/B thumbnail variants for a video."""
    import asyncio
    v = db.get(Video, video_id)
    if not v:
        raise HTTPException(404, "video not found")
    title = v.title or v.topic
    channel_name = ""
    with db.begin_nested() if db.in_transaction() else nullcontext():
        ch = db.get(Channel, v.channel_id)
        channel_name = ch.name if ch else ""

    async def _run():
        try:
            variants = await thumbnail_ai_svc.generate_ab_thumbnails(
                video_id, title, channel_name,
                clip_path=None,
                count=__import__("app.config", fromlist=["settings"]).settings.thumbnail_variant_count,
            )
            best = thumbnail_ai_svc.pick_best_variant(variants) or variants[0]
            from ..database import session_scope
            with session_scope() as sdb:
                vv = sdb.get(Video, video_id)
                if vv:
                    vv.thumbnail_path = best["path"]
                    vv.thumbnail_variants = [x["path"] for x in variants]
                    vv.predicted_ctr = best.get("ctr_score")
        except Exception as exc:
            log.exception("thumbnail regeneration failed: %s", exc)

    task = asyncio.create_task(_run())
    task.add_done_callback(lambda t: t.exception() if not t.cancelled() else None)
    return {"started": True, "video_id": video_id}


@router.post("/thumbnail-variants/{video_id}/pick/{variant_index}")
def pick_thumbnail_variant(video_id: int, variant_index: int,
                            db: Session = Depends(get_db)):
    """Manually pick a thumbnail variant as the active one for the video."""
    v = db.get(Video, video_id)
    if not v:
        raise HTTPException(404, "video not found")
    paths = v.thumbnail_variants or []
    if variant_index < 0 or variant_index >= len(paths):
        raise HTTPException(400, f"variant_index out of range (0-{len(paths) - 1})")
    v.thumbnail_path = paths[variant_index]
    db.commit()
    return {"picked": variant_index, "path": paths[variant_index]}


# Helper for the regenerate endpoint above (avoid extra import).
from contextlib import nullcontext  # noqa: E402
